# Generated by Django 5.2.17 on 2026-09-06 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_me', '0005_recipe_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='reserved', max_length=32)),
                ('provider_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('input_hash', models.CharField(max_length=64)),
                ('input', models.JSONField(default=dict)),
                ('content', models.JSONField(default=dict)),
                ('state', models.CharField(default='processing', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False), ('source_url__isnull', False), models.Q(('source_url', ''), _negated=True)), fields=('owner', 'source_url'), name='owned_recipe_source'),
        ),
        migrations.AddField(
            model_name='importdraft',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importdraft',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrape_me.recipe'),
        ),
        migrations.AddField(
            model_name='aiinvocation',
            name='draft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrape_me.importdraft'),
        ),
        migrations.AddConstraint(
            model_name='importdraft',
            constraint=models.UniqueConstraint(fields=('owner', 'key'), name='owned_import_key'),
        ),
    ]
