# Generated by Django 5.2.17 on 2026-09-06 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_me', '0006_aiinvocation_importdraft_usagecounter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_completions', to='scrape_me.recipe')),
            ],
        ),
    ]
