# Generated by Django 5.2.17 on 2026-09-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_me', '0007_cookingcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarterRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.JSONField()),
                ('provenance', models.JSONField()),
                ('source_markdown', models.TextField()),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
