# Generated by Django 5.2.17 on 2026-09-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_me', '0008_starterrecipe_recipe_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingcompletion',
            name='recipe_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='cookingcompletion',
            name='recipe_version',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
