# Generated by Django 5.2.17 on 2026-09-07 03:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill(apps, schema_editor):
    Recipe = apps.get_model("scrape_me", "Recipe")
    Starter = apps.get_model("scrape_me", "StarterRecipe")
    db = schema_editor.connection.alias
    for recipe in Recipe.objects.using(db).all().iterator():
        recipe.public_id = uuid.uuid4()
        # Existing incomplete work remains a draft. Existing saved valid content locks privately.
        valid = bool(recipe.title.strip()) and all(
            isinstance(v, list)
            and v
            and all(isinstance(x, str) and x.strip() for x in v)
            for v in (recipe.ingredients, recipe.instructions)
        )
        if valid:
            recipe.state = "finalized"
            recipe.finalized_at = recipe.updated_at
        recipe.save(using=db, update_fields=["public_id", "state", "finalized_at"])
    content_fields = (
        "title",
        "description",
        "author",
        "total_time",
        "yields",
        "source_url",
        "image",
        "ingredients",
        "instructions",
    )
    for starter in Starter.objects.using(db).all().iterator():
        content = {k: v for k, v in starter.content.items() if k in content_fields}
        provenance = dict(starter.provenance)
        if starter.content.get("notes"):
            provenance["source_notes"] = starter.content["notes"]
        recipe = Recipe.objects.using(db).create(
            public_id=uuid.uuid4(),
            state="finalized",
            visibility="public",
            finalized_at=timezone.now(),
            provenance=provenance,
            source_markdown=starter.source_markdown,
            type="url",
            **content
        )
        starter.recipe_id = recipe.pk
        starter.save(using=db, update_fields=["recipe"])


# JSON comparison includes content only. Personal annotations and visibility stay mutable.
IMMUTABILITY_SQL = """
CREATE FUNCTION flavorbuddy_recipe_immutable() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.state = 'finalized' THEN
      RAISE EXCEPTION 'Finalized recipes must be archived, not deleted' USING ERRCODE = '23514';
    END IF;
    RETURN OLD;
  END IF;
  IF TG_OP = 'UPDATE' AND OLD.public_id IS DISTINCT FROM NEW.public_id THEN
    RAISE EXCEPTION 'Recipe identity is permanent' USING ERRCODE = '23514';
  END IF;
  IF TG_OP = 'UPDATE' AND OLD.state = 'finalized' AND (
    (to_jsonb(OLD) - ARRAY['owner_id','notes','favorite','version','views','visibility','updated_at','archived_at'])
    IS DISTINCT FROM
    (to_jsonb(NEW) - ARRAY['owner_id','notes','favorite','version','views','visibility','updated_at','archived_at'])
  ) THEN
    RAISE EXCEPTION 'Finalized recipe content is immutable; create a variation' USING ERRCODE = '23514';
  END IF;
  IF NEW.state = 'finalized' THEN
    IF btrim(NEW.title) = '' OR jsonb_typeof(NEW.ingredients) <> 'array' OR jsonb_typeof(NEW.instructions) <> 'array' THEN
      RAISE EXCEPTION 'Finalized recipes require title, ingredients and instructions' USING ERRCODE = '23514';
    END IF;
    IF jsonb_array_length(NEW.ingredients) NOT BETWEEN 1 AND 200 OR jsonb_array_length(NEW.instructions) NOT BETWEEN 1 AND 200
       OR EXISTS (SELECT 1 FROM jsonb_array_elements(NEW.ingredients || NEW.instructions) item WHERE jsonb_typeof(item) <> 'string' OR btrim(item #>> '{}') = '') THEN
      RAISE EXCEPTION 'Finalized recipes require nonblank text ingredients and instructions' USING ERRCODE = '23514';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER recipe_content_immutable BEFORE INSERT OR UPDATE OR DELETE ON scrape_me_recipe
FOR EACH ROW EXECUTE FUNCTION flavorbuddy_recipe_immutable();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("scrape_me", "0009_cookingcompletion_recipe_snapshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recipe",
            name="owned_recipe_source",
        ),
        migrations.AddField(
            model_name="recipe",
            name="archived_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="finalized_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="inspired_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variations",
                to="scrape_me.recipe",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="public_id",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source_markdown",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("finalized", "Finalized")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")],
                default="private",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="starterrecipe",
            name="recipe",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_starter",
                to="scrape_me.recipe",
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        # Flush deferred FK checks before subsequent ALTER TABLE operations.
        migrations.RunSQL("SET CONSTRAINTS ALL IMMEDIATE", migrations.RunSQL.noop),
        migrations.AlterField(
            model_name="recipe",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("finalized_at__isnull", True),
                        ("state", "draft"),
                        ("visibility", "private"),
                    ),
                    models.Q(
                        ("finalized_at__isnull", False),
                        ("state", "finalized"),
                        ("visibility__in", ["private", "public"]),
                    ),
                    _connector="OR",
                ),
                name="recipe_lifecycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("inspired_by", models.F("id")), _negated=True),
                name="recipe_not_self_inspired",
            ),
        ),
        migrations.RunSQL(
            IMMUTABILITY_SQL,
            "DROP TRIGGER recipe_content_immutable ON scrape_me_recipe; DROP FUNCTION flavorbuddy_recipe_immutable();",
        ),
    ]
