# Generated by Django 5.2.17 on 2026-09-07 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scrape_me", "0008_starterrecipe_recipe_provenance"),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                ("resource_id", models.PositiveBigIntegerField(null=True)),
                ("status", models.PositiveSmallIntegerField()),
                ("request_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "recipes",
                    models.ManyToManyField(blank=True, to="scrape_me.starterrecipe"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("environment", models.CharField(max_length=20)),
                ("expires_at", models.DateTimeField()),
                ("daily_limit", models.PositiveIntegerField(default=1000)),
                ("minute_limit", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
                (
                    "catalogs",
                    models.ManyToManyField(blank=True, to="integrations.catalog"),
                ),
            ],
        ),
    ]
