# Generated by Django 5.2.17 on 2026-09-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appaudit',
            name='recipe_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
