# Generated by Django 5.2.17 on 2026-09-07 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photocleanup",
            name="not_before",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
