# Generated by Django 5.2.17 on 2026-09-07 02:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0002_photocleanup_not_before"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapabilityGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capture_enabled", models.BooleanField(default=False)),
                ("capture_daily_limit", models.PositiveIntegerField(default=3)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaptureJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.UUIDField()),
                ("input_hash", models.CharField(max_length=64)),
                ("image_key", models.CharField(max_length=200)),
                ("image_size", models.PositiveIntegerField()),
                ("state", models.CharField(default="queued", max_length=20)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("lease", models.UUIDField(null=True)),
                ("lease_expires", models.DateTimeField(null=True)),
                (
                    "available_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("preview", models.JSONField(default=list)),
                ("approved_ids", models.JSONField(default=list)),
                ("error_code", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(default="reserved", max_length=20)),
                ("units", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kitchen.capturejob",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="capturejob",
            constraint=models.UniqueConstraint(
                fields=("owner", "key"), name="owned_capture_key"
            ),
        ),
    ]
